# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-10 10:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0008_fundingsource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('type', models.CharField(choices=[('personal', 'personal'), ('business', 'business')], default='personal', max_length=10)),
                ('dwolla_type', models.CharField(choices=[('personal', 'personal'), ('business', 'business'), ('unverified', 'unverified')], default='unverified', max_length=10)),
                ('dwolla_id', models.CharField(blank=True, default=None, max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('verified', 'verified'), ('unverified', 'unverified')], default='unverified', max_length=10)),
                ('created_at', models.DateTimeField(blank=True, default=None, help_text='Created at dwolla.', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
            },
        ),
        migrations.CreateModel(
            name='FundingSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dwolla_id', models.CharField(blank=True, default=None, max_length=50, null=True, unique=True)),
                ('account_number', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('routing_number', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('status', models.CharField(choices=[('verified', 'verified'), ('unverified', 'unverified')], default='unverified', max_length=10)),
                ('type', models.CharField(choices=[('checking', 'checking'), ('savings', 'savings')], max_length=8)),
                ('typeb', models.CharField(choices=[('bank', 'bank'), ('balance', 'balance')], default=None, max_length=7, null=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('verification_type', models.CharField(choices=[('micro-deposit', 'micro deposit'), ('iav', 'instant verification')], default='micro-deposit', max_length=20)),
                ('md_status', models.CharField(blank=True, default=None, help_text='Micro-deposits verification status', max_length=20, null=True)),
                ('md_created_at', models.DateTimeField(blank=True, default=None, help_text='Micro-deposits created time.', null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finance.Account')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'funding source',
                'verbose_name_plural': 'funding sources',
            },
        ),
        migrations.CreateModel(
            name='FundingSourceIAVLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dwolla_id', models.CharField(max_length=255, unique=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Account')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'funding source iav log',
                'verbose_name_plural': 'funding source iav logs',
            },
        ),
        migrations.CreateModel(
            name='TransferDebt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.IntegerField(help_text='Current share on processing date.')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('processed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('account', models.ForeignKey(help_text='Debt account.', on_delete=django.db.models.deletion.CASCADE, related_name='accounts_transfers_user', to='finance.Account')),
            ],
            options={
                'ordering': ['-processed_at'],
                'verbose_name': 'transfer debt',
                'verbose_name_plural': 'transfers debt',
            },
        ),
        migrations.CreateModel(
            name='TransferDonkies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dwolla_id', models.CharField(blank=True, default=None, max_length=50, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processed', 'processed'), ('cancelled', 'cancelled'), ('failed', 'failed'), ('reclaimed', 'reclaimed')], default=None, max_length=9, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('initiated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('failure_code', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('is_initiated', models.BooleanField(default=False, help_text='Transfer initiated in Dwolla')),
                ('is_failed', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('processed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_sent', models.BooleanField(default=False, help_text='Money sent to Donkies LLC')),
                ('is_processed_to_user', models.BooleanField(default=False, help_text='Funds processed to TransferUser model.')),
                ('account', models.ForeignKey(help_text='Funding source user debit account.', on_delete=django.db.models.deletion.CASCADE, related_name='transfers_donkies', to='finance.Account')),
            ],
            options={
                'ordering': ['-updated_at'],
                'verbose_name': 'transfer donkies',
                'verbose_name_plural': 'transfers donkies',
            },
        ),
        migrations.CreateModel(
            name='TransferDonkiesFailed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dwolla_id', models.CharField(blank=True, default=None, max_length=50, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processed', 'processed'), ('cancelled', 'cancelled'), ('failed', 'failed'), ('reclaimed', 'reclaimed')], default=None, max_length=9, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('initiated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('failure_code', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('is_initiated', models.BooleanField(default=False, help_text='Transfer initiated in Dwolla')),
                ('is_failed', models.BooleanField(default=False)),
                ('account', models.ForeignKey(help_text='Funding source user debit account.', on_delete=django.db.models.deletion.CASCADE, to='finance.Account')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'transfer donkies failed',
                'verbose_name_plural': 'transfers donkies failed',
            },
        ),
        migrations.CreateModel(
            name='TransferUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cached_amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(to='bank.TransferDonkies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'transfer user',
                'verbose_name_plural': 'transfers user',
            },
        ),
        migrations.AddField(
            model_name='transferdebt',
            name='tu',
            field=models.ForeignKey(help_text='TransferUser transfer', on_delete=django.db.models.deletion.CASCADE, to='bank.TransferUser'),
        ),
        migrations.AlterUniqueTogether(
            name='fundingsourceiavlog',
            unique_together=set([('account', 'dwolla_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='fundingsource',
            unique_together=set([('account', 'name')]),
        ),
    ]
