# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dwolla_id', models.CharField(blank=True, default=None, max_length=50, null=True, unique=True)),
                ('account_number', models.CharField(max_length=100)),
                ('routing_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('verified', 'verified'), ('unverified', 'unverified')], default='unverified', max_length=10)),
                ('type', models.CharField(choices=[('checking', 'checking'), ('savings', 'savings')], max_length=8)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Account')),
            ],
            options={
                'verbose_name_plural': 'funding sources',
                'verbose_name': 'funding source',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': 'customer', 'verbose_name_plural': 'customers'},
        ),
    ]
