# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingsource',
            name='md_created_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Micro-deposits created time.', null=True),
        ),
        migrations.AddField(
            model_name='fundingsource',
            name='md_status',
            field=models.CharField(blank=True, default=None, help_text='Micro-deposits verification status', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fundingsource',
            name='verification_type',
            field=models.CharField(choices=[('micro-deposit', 'micro deposit'), ('iav', 'instant verification')], default='micro-deposit', max_length=20),
        ),
    ]
