# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20170116_0951'),
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingSourceIAVLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dwolla_id', models.CharField(max_length=255)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Account')),
            ],
            options={
                'verbose_name_plural': 'funding source iav logs',
                'verbose_name': 'funding source iav log',
                'ordering': ['-created_at'],
            },
        ),
    ]
