# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 21:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_created',
            field=models.BooleanField(default=False, help_text='Created in dwolla'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ssn',
            field=models.CharField(help_text='Last 4 digits', max_length=11, validators=[django.core.validators.RegexValidator(message='Should be XXX-XX-XXXX', regex='^\\d{3}\\-\\d{2}\\-\\d{4}$')]),
        ),
    ]
