# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 22:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20161201_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Should be 10 digits', regex='^\\d{10}$')]),
        ),
    ]
