# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_fundingsourceiavlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundingsourceiavlog',
            old_name='processed',
            new_name='is_processed',
        ),
        migrations.AlterField(
            model_name='fundingsource',
            name='account_number',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fundingsource',
            name='routing_number',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
