# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20170116_0951'),
        ('bank', '0003_auto_20170116_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingsourceiavlog',
            name='dwolla_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='fundingsourceiavlog',
            unique_together=set([('account', 'dwolla_id')]),
        ),
    ]
