# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-11 15:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('succeeded', 'succeeded'), ('failed', 'failed')], default='pending', max_length=9)),
                ('amount', models.IntegerField(help_text='Amount in cents.')),
                ('balance_transaction', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('captured', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('failure_code', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('failure_message', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('livemode', models.BooleanField(default=False)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('source', django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True)),
                ('created_at', models.DateTimeField(default=None, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='finance.Account')),
            ],
            options={
                'verbose_name_plural': 'charges',
                'verbose_name': 'charge',
                'ordering': ['created_at'],
            },
        ),
    ]
