# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 22:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonkiesUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('fb_id', models.BigIntegerField()),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('age_range', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('birthday', models.DateField(null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('link', models.CharField(max_length=250, null=True)),
                ('gender', models.CharField(max_length=25, null=True)),
                ('locale', models.CharField(max_length=50, null=True)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('user_timezone', models.CharField(max_length=25, null=True)),
                ('updated_time', models.DateTimeField(null=True)),
                ('verified', models.CharField(max_length=25, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether this user should be treated as staff. ', verbose_name='active')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates whether this user should be treated as superuser. ', verbose_name='active')),
                ('is_developer', models.BooleanField(default=False, help_text='Designates whether this user should be treated as developer. ', verbose_name='developer')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
            },
        ),
    ]
