# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donkiesoauth2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donkiesuser',
            name='email',
            field=models.EmailField(max_length=250, unique=True),
        ),
    ]
