#!/bin/bash

cd /home/vlad/dev/web/dj/d/donkies/project/donkies/

. ~/.venvs/donkies/bin/activate

if [ "$1" == "init" ]
then
clear

# celery should be running on init project

python manage.py cleanatrium
python manage.py pgcreatelocal
python manage.py initproject
python manage.py makemigrations
python manage.py makemigrations web
python manage.py makemigrations finance
python manage.py makemigrations bank
python manage.py migrate

python manage.py loaddata institutions

python manage.py createemails
python manage.py createsuperuser
python manage.py createtestusers
python manage.py createcustomers


elif [ "$1" == "migr" ]
then
clear
python manage.py makemigrations
python manage.py migrate

elif [ "$1" == "celery" ]
then
clear
export DJANGO_SETTINGS_MODULE=donkies.settings.development
celery worker -A donkies -l info -B

elif [ "$1" == "pgupload" ]
then
clear

pg_dump -U udonkies donkies -f db.dump --format=c
python manage.py pgdropremote
python manage.py pgcreateremote
pg_restore -h 159.203.137.132 -p 5432 -d donkies -U udonkies db.dump


elif [ "$1" == "pgdownload" ]
then
clear
python manage.py pgdroplocal
python manage.py pgcreatelocal
python manage.py pgdownload



elif [ "$1" == "test" ]
then
clear
# py.test -s donkies/tests/test_accounts.py
# py.test -s donkies/tests/test_auth.py
# py.test -s donkies/tests/test_atrium.py
# py.test -s donkies/tests/test_customers.py
# py.test -s donkies/tests/test_funding_sources.py
# py.test -s donkies/tests/test_institutions.py
# py.test -s donkies/tests/test_linking.py
# py.test -s donkies/tests/test_transactions.py
# py.test -s donkies/tests/test_facebook.py
# py.test -s donkies/tests/test_users.py

# Transfers
# py.test -s donkies/tests/transfers/test_accounts.py
# py.test -s donkies/tests/transfers/test_members.py
# py.test -s donkies/tests/transfers/test_transactions.py
py.test -s donkies/tests/transfers/test_transfer_donkies.py
# py.test -s donkies/tests/transfers/test_transfer_donkies_dwolla.py
# py.test -s donkies/tests/transfers/test_transfer_prepare.py
# py.test -s donkies/tests/transfers/test_transfer_user.py

else
clear
python manage.py runserver localhost:8000
fi
