# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='is_update',
            field=models.BooleanField(default=True, help_text='Update credentials of the institution on scheduled task'),
        ),
    ]
