# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_dwolla_created',
        ),
        migrations.AlterField(
            model_name='account',
            name='is_funding_source',
            field=models.BooleanField(default=False, help_text='For debit account. Funding source for transfer.'),
        ),
    ]
