# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-03 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_processed', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Item')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': 'fetch transactions',
                'verbose_name': 'fetch transactions',
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_processed',
            field=models.NullBooleanField(default=False, help_text='Internal flag. Roundup has been applied'),
        ),
    ]
