# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
