# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-06 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='additional_info',
            field=models.CharField(blank=True, default=None, help_text='Used for manual debt accounts.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='is_manual',
            field=models.BooleanField(default=False, help_text='Used for debt accounts. Not exist in Plaid.'),
        ),
    ]
