# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-11 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='stripe_token',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
    ]
