# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-31 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_created',
            field=models.BooleanField(default=False),
        ),
    ]
