# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 17:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20161111_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'initiated'), ('REQUESTED', 'requested'), ('CHALLENGED', 'challenged'), ('RECEIVED', 'received'), ('TRANSFERRED', 'transferred'), ('PROCESSED', 'processed'), ('COMPLETED', 'completed'), ('PREVENTED', 'prevented'), ('DENIED', 'denied'), ('HALTED', 'halted')], default='INITIATED', max_length=50),
        ),
    ]
