# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20170315_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, default=None, help_text='For debt accounts only. Set by user.', max_length=100, null=True),
        ),
    ]
