# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20170202_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='finance.Member'),
        ),
    ]
