# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20161117_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='roundup',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True),
        ),
    ]
