# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20170117_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='check_number_string',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
