# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-03 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20170503_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date'], 'verbose_name': 'transaction', 'verbose_name_plural': 'transactions'},
        ),
    ]
