# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20170116_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_funding_source',
            new_name='is_funding_source_for_transfer',
        ),
    ]
