# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20170118_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferPrepare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roundup', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dt', models.DateField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='finance.Account')),
            ],
            options={
                'ordering': ['-dt'],
                'verbose_name': 'transfer prepare',
                'verbose_name_plural': 'transfers prepare',
            },
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ['-dt'], 'verbose_name': 'transfer', 'verbose_name_plural': 'transfers'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='Internal flag. Roundup has been transferred'),
        ),
    ]
