# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20170118_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferDonkies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('received_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('processed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_sent', models.BooleanField(default=False, help_text='Money sent to Donkies LLC')),
                ('is_received', models.BooleanField(default=False, help_text='Money received by Donkies LLC')),
                ('is_processed_to_user', models.BooleanField(default=False, help_text='Funds processed to TransferUser model.')),
                ('account', models.ForeignKey(help_text='Funding source debit account.', on_delete=django.db.models.deletion.CASCADE, related_name='transfers_donkies', to='finance.Account')),
            ],
            options={
                'verbose_name': 'transfer donkies',
                'ordering': ['-created_at'],
                'verbose_name_plural': 'transfers donkies',
            },
        ),
        migrations.RenameModel(
            old_name='Transfer',
            new_name='TransferUser',
        ),
        migrations.AlterModelOptions(
            name='transferprepare',
            options={'ordering': ['-created_at'], 'verbose_name': 'transfer prepare', 'verbose_name_plural': 'transfers prepare'},
        ),
        migrations.RenameField(
            model_name='transferprepare',
            old_name='dt',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='transferprepare',
            name='processed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transferprepare',
            name='account',
            field=models.ForeignKey(help_text='Debit account.', on_delete=django.db.models.deletion.CASCADE, related_name='transfers_prepare', to='finance.Account'),
        ),
    ]
