# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-10 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_account_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
