# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-26 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_institution_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='lender',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
