# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20170118_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'transfer user', 'verbose_name_plural': 'transfers user'},
        ),
        migrations.RemoveField(
            model_name='transferuser',
            name='account_from',
        ),
        migrations.RemoveField(
            model_name='transferuser',
            name='account_to',
        ),
        migrations.RemoveField(
            model_name='transferuser',
            name='dt',
        ),
        migrations.AddField(
            model_name='transferuser',
            name='account',
            field=models.ForeignKey(default=None, help_text='Debt account.', on_delete=django.db.models.deletion.CASCADE, related_name='transfers_user', to='finance.Account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferuser',
            name='processed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='transferuser',
            name='share',
            field=models.IntegerField(default=1, help_text='Current share on processing date.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferuser',
            name='td',
            field=models.ForeignKey(default=None, help_text='Related TransferDonkies amount', on_delete=django.db.models.deletion.CASCADE, to='finance.TransferDonkies'),
            preserve_default=False,
        ),
    ]
