# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20170118_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='is_processed',
            field=models.NullBooleanField(default=False, help_text='Internal flag. Roundup has been transferred'),
        ),
    ]
