# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20170119_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferdonkies',
            name='dwolla_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transferdonkies',
            name='initiated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='transferdonkies',
            name='is_initiated',
            field=models.BooleanField(default=False, help_text='Transfer initiated in Dwolla'),
        ),
        migrations.AddField(
            model_name='transferdonkies',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transferdonkies',
            name='account',
            field=models.ForeignKey(help_text='Funding source user debit account.', on_delete=django.db.models.deletion.CASCADE, related_name='transfers_donkies', to='finance.Account'),
        ),
    ]
