# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-10 12:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0008_fundingsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferCalculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roundup_sum', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('total_roundaps', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('min_amount', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('transactions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transactions', to='finance.Transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_calulations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
