# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-10 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_transfercalculation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfercalculation',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10, null=True),
        ),
    ]
