# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20170119_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferDonkiesFailed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dwolla_id', models.CharField(blank=True, default=None, max_length=50, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processed', 'processed'), ('cancelled', 'cancelled'), ('failed', 'failed'), ('reclaimed', 'reclaimed')], default=None, max_length=9, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('failure_code', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('failed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('account', models.ForeignKey(help_text='Funding source user debit account.', on_delete=django.db.models.deletion.CASCADE, to='finance.Account')),
            ],
            options={
                'verbose_name': 'transfer donkies failed',
                'verbose_name_plural': 'transfers donkies failed',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transferdonkies',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('processed', 'processed'), ('cancelled', 'cancelled'), ('failed', 'failed'), ('reclaimed', 'reclaimed')], default=None, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='transferdonkies',
            name='created_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
