# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-10 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_auto_20170810_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfercalculation',
            name='roundup_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transfercalculation',
            name='total_roundaps',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
