# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_auto_20170119_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferdonkies',
            name='is_received',
        ),
        migrations.RemoveField(
            model_name='transferdonkies',
            name='received_at',
        ),
    ]
