# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-10 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_auto_20170810_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfercalculation',
            name='transactions',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_calculation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.TransferCalculation'),
        ),
    ]
