# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_auto_20170119_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferdonkies',
            name='failed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='transferdonkies',
            name='failure_code',
            field=models.CharField(blank=True, default=None, max_length=4, null=True),
        ),
    ]
