# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-11 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_auto_20170810_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingsource',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funding_items', to='finance.Item'),
        ),
    ]
