# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_auto_20170119_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferdonkies',
            name='failed_at',
        ),
        migrations.RemoveField(
            model_name='transferdonkiesfailed',
            name='failed_at',
        ),
        migrations.AddField(
            model_name='transferdonkies',
            name='is_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transferdonkiesfailed',
            name='initiated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='transferdonkiesfailed',
            name='is_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transferdonkiesfailed',
            name='is_initiated',
            field=models.BooleanField(default=False, help_text='Transfer initiated in Dwolla'),
        ),
        migrations.AddField(
            model_name='transferdonkiesfailed',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
