# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-21 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_auto_20170817_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pause',
            field=models.BooleanField(default=False),
        ),
    ]
