# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-31 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_item_pause'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingsource',
            name='dwolla_balance_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
