# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-01 12:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_fundingsource_dwolla_balance_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_links', django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=255)),
                ('created', models.DateTimeField()),
                ('transfer_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processed', 'processed')], default='pending', max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='finance.Account')),
                ('funding_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_sources', to='finance.FundingSource')),
            ],
        ),
    ]
