# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-06 16:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_auto_20170904_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferbalance',
            name='clearing',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='transferbalance',
            name='transfer_direction',
            field=models.CharField(choices=[('account --> dwolla_balance', 'account --> dwolla_balance'), ('dwolla_balance --> account', 'dwolla_balance --> account')], default='account --> dwolla_balance', max_length=255),
        ),
    ]
