# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-08 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_auto_20170906_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='pause',
        ),
        migrations.AddField(
            model_name='account',
            name='pause',
            field=models.BooleanField(default=False),
        ),
    ]
