# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 16:12
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('encrypted_id', models.CharField(default='', max_length=32)),
                ('guid', models.CharField(blank=True, default=None, help_text='Atrium guid', max_length=100, null=True, unique=True)),
                ('identifier', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('email', models.EmailField(default=None, max_length=255, null=True, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, default='', max_length=50)),
                ('birthday', models.DateField(blank=True, default=None, null=True)),
                ('confirmation_token', models.CharField(blank=True, max_length=255)),
                ('confirmed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('reset_token', models.CharField(max_length=255)),
                ('reset_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('last_access_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_admin', models.BooleanField(default=False, verbose_name='admin')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser')),
                ('fb_id', models.CharField(default=None, max_length=100, null=True, unique=True)),
                ('fb_response', django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True)),
                ('is_atrium_created', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Users',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('txt', models.TextField()),
                ('html', models.TextField()),
            ],
            options={
                'verbose_name': 'email',
                'verbose_name_plural': 'emails',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Emailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_to', models.EmailField(max_length=100)),
                ('email_from', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('txt', models.TextField()),
                ('html', models.TextField()),
                ('report', models.TextField(default='')),
                ('sent', models.BooleanField(default=False)),
                ('result', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_code', models.CharField(default='', max_length=10)),
                ('level', models.CharField(default='', max_length=8)),
                ('logger_name', models.CharField(default='', max_length=20)),
                ('module', models.CharField(default='', max_length=100)),
                ('thread', models.CharField(default='', max_length=50)),
                ('thread_name', models.CharField(default='', max_length=100)),
                ('exc_info', models.CharField(default='', max_length=255)),
                ('stack_info', models.TextField(default='')),
                ('message', models.TextField(default='')),
                ('dt', models.DateTimeField(auto_now_add=True, verbose_name='date')),
            ],
            options={
                'verbose_name': 'logging',
                'verbose_name_plural': 'logging',
                'ordering': ['-dt'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('value', models.CharField(blank=True, default='', max_length=255)),
                ('info', models.CharField(blank=True, default='', max_length=255)),
                ('type', models.SmallIntegerField(blank=True, choices=[(1, 'str'), (2, 'int')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expire_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'token',
                'verbose_name_plural': 'tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
