# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='minimum_transfer_amount',
            field=models.IntegerField(default=50, help_text='Minimum amount for transfer.'),
        ),
    ]
