# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-13 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_closed_account',
            field=models.BooleanField(default=False, help_text='User closed account in Donkies'),
        ),
    ]
