# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-10 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_even_roundup',
            field=models.BooleanField(default=False, help_text='Roundup even amounts $1.00, $2.00 etc'),
        ),
    ]
