# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='guid',
            field=models.CharField(blank=True, default=None, help_text='atrium guid', max_length=100, null=True, unique=True),
        ),
    ]
