# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_auto_transfer',
            field=models.BooleanField(default=True, help_text='Auto transfer when reach minimum amount'),
        ),
    ]
