# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-02 09:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_user_last_alert_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ipAddress',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], default='personal', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='ssn',
            field=models.CharField(default=None, help_text='Last 4 digits', max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Should be XXXX', regex='^\\d{4}$')]),
        ),
    ]
