# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-03 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20170802_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dwolla_verified_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
