# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-04 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20170804_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address1',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default='city', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
