# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-04 14:49
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20170804_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2017, 8, 4, 14, 49, 55, 693540), help_text='YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='postal_code',
            field=models.CharField(default='12345', max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Should be 5 digits', regex='^\\d{5}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='ssn',
            field=models.CharField(default='4242', help_text='Last 4 digits', max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Should be XXXX', regex='^\\d{4}$')]),
        ),
    ]
