# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-04 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20170804_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=None, help_text='YYYY-MM-DD', null=True),
        ),
    ]
