# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-07 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20170804_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='funding_sources_url',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
