# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-25 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20170829_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
    ]
