# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-30 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_user_is_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_days',
            field=models.IntegerField(default=0),
        ),
    ]
