# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-04 12:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_user_active_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_success', models.BooleanField()),
                ('ip_address', models.GenericIPAddressField()),
                ('auth_datetime', models.DateTimeField(auto_now_add=True)),
                ('user_attempted', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_attempted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
