# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-04 17:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_authenticationevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationevent',
            name='user_attempted',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_attempted', to=settings.AUTH_USER_MODEL),
        ),
    ]
